### ISSUE TITLE
Py_ver

### ISSUE THREAD

**Issue by profLewis** [jgomezdans/geog_docker#8]
This is great and, so far as I can see, the only config anyone would ever manned change would be in the Dockerfiles. For py_ver (anything else?).

Python version is defined in py_ver in the Dockerfiles, but also in the environment.yaml. These might not be consistent.

You could drop the python>=3.7 restriction in environment.yaml and just use the constraint in the dockerfile.

For using the repo for non-docker setup, see my comments in other issue I raised on jupyter-notebook. If the non-docker setter-upper parsed the Dockerfile, they would pick up the py_ver from there.

Or ... move config info out of docker args and into a config file and red from that. That might be cleaner.

**Comment by profLewis** [comment]
So, this is the potentially 
Non generic config stuff in the Dockerfile that might be moved to a config.


FROM jupyter/minimal-notebook:latest
# name your environment and choose python 3.x version
ARG conda_env=uclgeog
ARG py_ver=3.7

**Comment by jgomezdans** [comment]
The `py_ver` isn't actually used in the Dockerfile, it's there because I forgot to delete it. The only one that is current is the `environment.yml` one.

I have strived to get the Docker file to be generic, but there's issues when installing the extensions from conda (some of them were buggy, some of them require extra commands to run into notebooks and/or lab, ...). Not sure what the best way around this would be.

**Comment by profLewis** [comment]
perfect. so take it out of dockerfile?

Its a great generic job.

My only worry is windows with all of this ...
